language: node_js
node_js:
- node
env:
  - ISSUER=REBUS_READER
  - AUDIENCE=REBUS_API
  - SECRETORKEY=this_is_a_testing_secret
# From travis-ci.com: "The default user for accessing the local PostgreSQL server is postgres with a blank password."
# The database name (created below) is: "travis_ci_test"
services:
- postgresql
before_install:
- openssl aes-256-cbc -K $encrypted_28143c166499_key -iv $encrypted_28143c166499_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: gae
  keyfile: google-keyfile.json
  project: thematic-cider-139815
  config: app-development.yaml
  skip_cleanup: true
  on:
    branch: master
